### ISSUE TITLE
Moving from global environment variables to standard variable handling.

### ISSUE THREAD

**Issue by seabbs** [jurrr/modelplotr#12]
Hi Jurrr, 

In adding support for `h2o` I looked in more detail at your package - in particular in trying to get tests set up. I saw that throughout you have made use of global assignment of variables rather than passing out of functions. I get that this is a design choice and may make things easier for non-R users but I found it very difficult to work around. I can see that any future work using this package would also be made more difficult by this choice. 

Do you have any thoughts about moving to a more standard R package structure of returning function outputs rather than assigning? Not sure where you are in the development cycle on this so it may not be an option. If you are interested I am very happy to look into this in another pull request. 

Thanks, 

Sam

**Comment by jurrr** [comment]
in the CRAN release (v1.0), there is no writing to global environment any more
