### ISSUE TITLE
R version

### ISSUE THREAD

**Issue by covijt** [jurrr/modelplotr#18]
package modelplotr not available (for R version 3.4.4 & 3.5.1).

When could we expect the package to be compatible with the above R versions.

Best regards,

**Comment by jurrr** [comment]
hi covijt, modelplotr is available for R version >= 3.1.0.

**Comment by covijt** [comment]
Hi jurr, I am a data scientist for the last 15 years and and i maintain my comment.
Of course in the answer "R version >+ 3.1.0" is a simple answer but have you yourself tried to install the package in R versions suggested in my initial comment?

**Comment by modelplot** [comment]
Dear Covijt, sorry to hear that insyalling modelplotr was unsuccessfull for you. We did however test on all r releases from 3.1 up until current development version extensively. And I did retest on the versions today before closing the issue. What are the exact problems you run into? Did you install required dependencies?

**Comment by covijt** [comment]
Dear jurr, as suggested all required dependency's have been installed. Unfortunately, still can't install modelplotr on R version 3.4.4 and 3.5.1. Please find herewith a txt log file concerning post trial installation.

Kind regards
[packageInstallLog.txt](https://github.com/jurrr/modelplotr/files/3125385/packageInstallLog.txt)

**Comment by modelplot** [comment]
Hi covijt, I think the issue is that dependency rlang >= 3.1.0 is not met:

namespace 'rlang' 0.2.1 is being loaded, but >= 0.3.1 is required

Please try updating rlang and reinstall modelplotr. This should solve your issue. 

Kimd regards, 

Jurriaan

**Comment by covijt** [comment]
Bonjour jurr, you are quite right. Now I installed rlang >= 0.3.1 and I still can't install the package wrap in a tar.gz file. So instead I use the modelplotr 1.0.0.zip file and admittedly, installation went fine and so does the package.

**Comment by modelplot** [comment]
👍🏻happy modelplotting!

**Comment by covijt** [comment]
Thank you Jurriaan !
