### ISSUE TITLE
Is picking a random observation really random?

### ISSUE THREAD

**Issue by laresbernardo** [jurrr/modelplotr#19]
Hello guys. I've got a concept question about the cumulative gains plot. 

I understand perfectly how the wizard (optimal) curve is calculated, the model's cumulative gain curve as well. But, about the random line with a 45 degree slope, I've got the following suspicion: I get that it should start in 0 (non picked, impossible to get anything) and end in 100% (if everything is selected, you'll get all cases as well). But, if the dataset is not truly balanced (50/50 for target vs non-target cases), if I pick a random observation of any of the percentiles (supposing they have all the same distribution because they are random), wouldn't the probability of picking an observation of our target class less or more than 50%? And also, if I have 10 percentiles, go to the 5th, and pick all of those cases, I wouldn't have 50% of my target observations but the amount relative to the relation between target and non-target observations, right?

**Comment by jurrr** [comment]
Hi Lares,

Thanks for your question. The cumulative gains tells you at a given
percentile what percentage of all target cases you have selected.
Therefore, the reference line for random selections is indeed a 45 degrees
line: When you select 30 % of all cases randomly (Hence decile 3 or
percentile 30) this selection will hold 30% of all target class cases in
the total set. Irrespective of how small or large the total number of
target classes is. The trick is to understand that the y axis of the cum
gains chart represents the % of all the target class cases in the set, not
the % of target class cases that are present in a specific decile ( thats
the response chart).

Hope this clarifies how to interpret. If not or not fully, please have a
look at our blog or vignette in which we try to explain the plots and
interpretations (modelplot.github.io).

Jurriaan
Op do 11 jul. 2019 om 16:54 schreef laresbernardo <notifications@github.com>

**Comment by laresbernardo** [comment]
Thanks, that's what I thought could be but wasn't 100% certain. Thanks for taking the time @jurrr 👍
