### ISSUE TITLE
Support h2o models?

### ISSUE THREAD

**Issue by seabbs** [jurrr/modelplotr#8]
Package looks great.

Any plans to extend the supported models beyond `mlr` and `caret and/or add the ability to add custom prediction functions? 

Support for `h2o` would be ideal (https://cran.r-project.org/web/packages/h2o/index.html). If you point me in the right direction I may be able to fork, add support and submit a pull request. 

Thanks, 

Sam

**Comment by jurrr** [comment]
Hi Sam, 

Thanks for your suggestion and offer to add h2o support to modelplotr! 

Support for caret and mlr is managed in the _**prepare_scores_and_deciles()**_ function (_R -> dataprepmodelplots.R -> prepare_scores_and_deciles()_). From the components of the models specified in the parameters, it is derived whether the model is developed with caret or mlr. For both mlr and caret, the predict functionality is used to apply a binary/multiclass predictive model to datasets and to make sure the output has format and naming required for the next function: _aggregate_over_deciles()_.

You could already use modelplotr with your h2o models, though! You just have to perform the scoring (h2o.predict()) yourself and make sure the scored dataframe looks like the dataframe needed for aggregate_over_deciles(). In the documentation, you can find the details on this, have a look at **?modelplotr::aggregate_over_deciles()** and read the part below **_When you build scores_and_deciles yourself_** for the details.
 
Cheers,
Jurriaan

**Comment by seabbs** [comment]
Hi Jurriaan, 

Thanks for the helpful pointers - opened a pull request with `h2o` support. Also opened a few other issues with some thoughts based on looking in greater detail at the package - feel free to ignore these as may be down to personal taste. 

Sam

**Comment by jurrr** [comment]
h2o support is added - thanks to seabbs
